import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import clientsRouter from "./clients";
import vendorsRouter from "./vendors";
import productsRouter from "./products";
import bundlesRouter from "./bundles";
import salesOrdersRouter from "./salesOrders";
import purchaseOrdersRouter from "./purchaseOrders";
import inventoryRouter from "./inventory";
import assemblyRouter from "./assembly";
import artworkRouter from "./artwork";
import shipmentsRouter from "./shipments";
import invoicesRouter from "./invoices";
import analyticsRouter from "./analytics";
import contactsRouter from "./contacts";
import leadsRouter from "./leads";
import quotesRouter from "./quotes";
import activitiesRouter from "./activities";
import catalogRouter from "./catalog";
import operationsRouter from "./operations";
import notificationsRouter from "./notifications";
import settingsRouter from "./settings";
import companiesRouter from "./companies";
import sampleOrdersRouter from "./sampleOrders";
import fixedAssetsRouter from "./fixedAssets";
import productionOrdersRouter from "./productionOrders";
import orderProcessingFormsRouter from "./orderProcessingForms";
import uploadsRouter from "./uploads";
import creditNotesRouter from "./creditNotes";
import auditLogsRouter from "./auditLogs";
import reportsRouter from "./reports";
import servicesRouter from "./services";
import catalogueSharesRouter from "./catalogueShares";
import advanceReceiptsRouter from "./advanceReceipts";
import proformaInvoicesRouter from "./proformaInvoices";
import vendorProductsRouter from "./vendorProducts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(companiesRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(vendorsRouter);
router.use(productsRouter);
router.use(bundlesRouter);
router.use(salesOrdersRouter);
router.use(purchaseOrdersRouter);
router.use(inventoryRouter);
router.use(assemblyRouter);
router.use(artworkRouter);
router.use(shipmentsRouter);
router.use(invoicesRouter);
router.use(analyticsRouter);
router.use(contactsRouter);
router.use(leadsRouter);
router.use(quotesRouter);
router.use(activitiesRouter);
router.use(catalogRouter);
router.use(operationsRouter);
router.use(notificationsRouter);
router.use(settingsRouter);
router.use(sampleOrdersRouter);
router.use(fixedAssetsRouter);
router.use(productionOrdersRouter);
router.use(orderProcessingFormsRouter);
router.use(uploadsRouter);
router.use(creditNotesRouter);
router.use(auditLogsRouter);
router.use(reportsRouter);
router.use(servicesRouter);
router.use(catalogueSharesRouter);
router.use(advanceReceiptsRouter);
router.use(proformaInvoicesRouter);
router.use(vendorProductsRouter);

export default router;
